/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan14;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fazriachyar
 */
public class ExceptionHandling extends javax.swing.JFrame {
    private static String fileNameInput;
    /**
     * Creates new form ExceptionHandling
     */
    public ExceptionHandling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        textFieldInput = new javax.swing.JTextField();
        buttonProses = new javax.swing.JButton();
        radioButtonException = new javax.swing.JRadioButton();
        radioButtonNoException = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exception Fazri Achyar Rozaq");
        setResizable(false);

        buttonProses.setText("Proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonGroup.add(radioButtonException);
        radioButtonException.setText("Dengan Exception Handling");

        buttonGroup.add(radioButtonNoException);
        radioButtonNoException.setText("Tanpa Exception Handling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radioButtonNoException, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButtonException, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldInput, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonProses)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProses))
                .addGap(18, 18, 18)
                .addComponent(radioButtonException)
                .addGap(18, 18, 18)
                .addComponent(radioButtonNoException)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        if (!radioButtonException.isSelected() && !radioButtonNoException.isSelected()){
            JOptionPane.showMessageDialog(this,"Silahkan tentukan salah satu pilihan dibawah terlebih dahulu");
        } else {
            JFileChooser inputFileChooser = new JFileChooser();
            inputFileChooser.showOpenDialog(null);
            File selectedFile = inputFileChooser.getSelectedFile();
            
            if(radioButtonException.isSelected()){
                try{
                    if (selectedFile.exists()) {
                        textFieldInput.setText(selectedFile.getAbsolutePath());
                        JOptionPane.showMessageDialog(this, "File ditemukan : " + selectedFile.getAbsolutePath());
                    } else {
                        JOptionPane.showMessageDialog(this, "File tidak ditemukan : " + selectedFile.getAbsolutePath());
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this,"Pemilihan file dibatalkan");
                }
            } else if (radioButtonNoException.isSelected()){
                if (selectedFile.exists()) {
                    textFieldInput.setText(selectedFile.getAbsolutePath());
                    JOptionPane.showMessageDialog(this, "File ditemukan : " + selectedFile.getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(this, "File tidak ditemukan : " + selectedFile.getAbsolutePath());
                }
            }
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExceptionHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExceptionHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExceptionHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExceptionHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExceptionHandling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonProses;
    private javax.swing.JRadioButton radioButtonException;
    private javax.swing.JRadioButton radioButtonNoException;
    private javax.swing.JTextField textFieldInput;
    // End of variables declaration                   
}
